[package]
name = "candle-birnn"
version = "0.1.0"
edition = "2021"
description = "implement Pytorch LSTM and BiDirectional LSTM with Candle"
readme = "README.md"
repository = "https://github.com/kigichang/candle-birnn"
license-file = "LICENSE"
keywords = ["candle", "lstm", "pytorch"]


[dependencies]
candle-core = "0.6.0"
candle-nn = "0.6.0"

[dev-dependencies]
anyhow = "1.0.86"
